from app_db import db
from sqlalchemy import Column


class Financial(db.Model):
  id: Column = db.Column(db.Integer, primary_key=True, nullable=False)
  symbol_id: Column = db.Column(db.Integer, nullable=False)
  year: Column = db.Column(db.Integer, nullable=False)
  quarter: Column = db.Column(db.Integer, nullable=False)
  quarter_end_date: Column = db.Column(db.DateTime, nullable=False)
  file_date: Column = db.Column(db.DateTime)
  market_cap: Column = db.Column(db.Numeric(18, 2))
  revenue: Column = db.Column(db.Numeric(18, 2))
  gross_profit: Column = db.Column(db.Numeric(18, 2))
  operating_income: Column = db.Column(db.Numeric(18, 2))
  net_income: Column = db.Column(db.Numeric(18, 2))
  current_assets: Column = db.Column(db.Numeric(18, 2))
  ttl_assets: Column = db.Column(db.Numeric(18, 2))
  current_liabilities: Column = db.Column(db.Numeric(18, 2))
  ttl_liabilities: Column = db.Column(db.Numeric(18, 2))
  ttl_equity: Column = db.Column(db.Numeric(18, 2))
  revenue_growth: Column = db.Column(db.Numeric(18, 2))
  revenue_qq_growth: Column = db.Column(db.Numeric(18, 2))
  nopat_growth: Column = db.Column(db.Numeric(18, 2))
  nopat_qq_growth: Column = db.Column(db.Numeric(18, 2))
  net_income_growth: Column = db.Column(db.Numeric(18, 2))
  net_income_qq_growth: Column = db.Column(db.Numeric(18, 2))
  free_cash_flow: Column = db.Column(db.Numeric(18, 2))
  current_ratio: Column = db.Column(db.Numeric(18, 2))
  debt_to_equity_ratio: Column = db.Column(db.Numeric(18, 2))
  pe_ratio: Column = db.Column(db.Numeric(18, 2))
  pb_ratio: Column = db.Column(db.Numeric(18, 2))
  div_payout_ratio: Column = db.Column(db.Numeric(18, 2))
  roe: Column = db.Column(db.Numeric(18, 2))
  roa: Column = db.Column(db.Numeric(18, 2))
